### ISSUE TITLE
Pantheon 7 updates 2022-10-19

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#10]
#### [pantheon.wingpanel-indicator-a11y](https://github.com/elementary/wingpanel-indicator-a11y): [1.0.0 → HEAD](https://github.com/elementary/wingpanel-indicator-a11y/compare/1.0.0...HEAD)

- [x] [<code>l10n: Correctly setup the locales (#48)</code>](https://github.com/elementary/wingpanel-indicator-a11y/commit/fb8412d56bc1c42b70e8ee41b837e8024e1297f7)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Remove wingpanel deprecations (#49)</code>](https://github.com/elementary/wingpanel-indicator-a11y/commit/0480d77c0dc5d727749db6a2273fa3057491a74a)
- [x] [<code>Update a11y.appdata.xml.in</code>](https://github.com/elementary/wingpanel-indicator-a11y/commit/fb8254b880cd13a494312bb9a848ffc53caa8fdf)
- [x] [<code>Release 1.0.1 (#51)</code>](https://github.com/elementary/wingpanel-indicator-a11y/commit/554441740cb806a4b4bf32afd45fc4c3dd11179b)
  - <sub>Tags: <code>1.0.1</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.wingpanel-indicator-session](https://github.com/elementary/wingpanel-indicator-session): [2.3.0 → HEAD](https://github.com/elementary/wingpanel-indicator-session/compare/2.3.0...HEAD)

- [x] [<code>l10n: Correctly setup the locales (#162)</code>](https://github.com/elementary/wingpanel-indicator-session/commit/e85032da8e923df4589dc75ccded10026b6c1cd7)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Indicator: replace OverlayIcon with Gtk.Image (#167)</code>](https://github.com/elementary/wingpanel-indicator-session/commit/0ea9a3b3f5cc4da9c6c569f019393cb107692901)
- [x] [<code>Update codestyle (#169)</code>](https://github.com/elementary/wingpanel-indicator-session/commit/b26e7f1dabfe554aff3d763f9c16972a35ab1e89)
- [x] [<code>Update session.appdata.xml.in</code>](https://github.com/elementary/wingpanel-indicator-session/commit/b1fef445c574c9c24859684f6c784143024b1c2d)
- [x] [<code>Release 2.3.1 (#170)</code>](https://github.com/elementary/wingpanel-indicator-session/commit/ade43580559fb7dff8c2ae725677c700482d661c)
  - <sub>Tags: <code>2.3.1</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.wingpanel-indicator-notifications](https://github.com/elementary/wingpanel-indicator-notifications): [6.0.6 → HEAD](https://github.com/elementary/wingpanel-indicator-notifications/compare/6.0.6...HEAD)

- [x] [<code>Update notifications.appdata.xml.in</code>](https://github.com/elementary/wingpanel-indicator-notifications/commit/0319f744be628e130a1aa4933f92c8f6d99e7dba)
- [x] [<code>Release 6.0.7 (#250)</code>](https://github.com/elementary/wingpanel-indicator-notifications/commit/219af018e13312de47b5d65d3ab7a2a440fe8c66)
  - <sub>Tags: <code>6.0.7</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.wingpanel-indicator-nightlight](https://github.com/elementary/wingpanel-indicator-nightlight): [2.1.0 → HEAD](https://github.com/elementary/wingpanel-indicator-nightlight/compare/2.1.0...HEAD)

- [x] [<code>Update POTFILES to fix build (#89)</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/591919379414e9012316a033b5236a0f4fbe9392)
- [x] [<code>Revert "Deleted translation using Weblate (English (United States))"</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/bffdd46e9d6b879187bd56d8c87d1d2a465fd01a)
- [x] [<code>Revert "Deleted translation using Weblate (English (United States))"</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/a616221e2d57aa892b3d076593f74a45d4baf3f6)
- [x] [<code>po: Remove en_US (#90)</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/a383f68eb0c97583509b47f28452f6a0f3cc9be4)
- [x] [<code>l10n: Correctly setup the locales (#91)</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/4e15f71ed958df3569b2f1e224b9fb18613281f1)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Update nightlight.appdata.xml.in</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/370456f74ba4f20f33d4ae0e9f7220784921dad6)
- [x] [<code>Release 2.1.1 (#93)</code>](https://github.com/elementary/wingpanel-indicator-nightlight/commit/0296cfd13420ca686b2b7cab66d0fe4add19a3ec)
  - <sub>Tags: <code>2.1.1</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.wingpanel-indicator-network](https://github.com/elementary/wingpanel-indicator-network): [2.3.3 → HEAD](https://github.com/elementary/wingpanel-indicator-network/compare/2.3.3...HEAD)

- [x] [<code>Update network.appdata.xml.in</code>](https://github.com/elementary/wingpanel-indicator-network/commit/fdbe6437237c78229fd2e5e0d4765c703ae862ff)
- [x] [<code>Release 2.3.4 (#253)</code>](https://github.com/elementary/wingpanel-indicator-network/commit/799af503f73ec927e91031aea77e6c585dd808d8)
  - <sub>Tags: <code>2.3.4</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.wingpanel-indicator-datetime](https://github.com/elementary/wingpanel-indicator-datetime): [2.4.0 → HEAD](https://github.com/elementary/wingpanel-indicator-datetime/compare/2.4.0...HEAD)

- [x] [<code>Update codestyle (#302)</code>](https://github.com/elementary/wingpanel-indicator-datetime/commit/638a99085317966211a17cac7ed993349616c4e5)
- [x] [<code>GridDay: Do not connect to the notify signal for the property (#305)</code>](https://github.com/elementary/wingpanel-indicator-datetime/commit/845ac1345124571fe995ab7138d5dfe4d29847e9)
- [x] [<code>Update datetime.appdata.xml.in</code>](https://github.com/elementary/wingpanel-indicator-datetime/commit/47309e16f828b6c4f8aa4ad71500d5af3bc61bfd)
- [x] [<code>Release 2.4.1 (#306)</code>](https://github.com/elementary/wingpanel-indicator-datetime/commit/80b746494c9a36ea4b6fc3de3a140716e17abbd9)
  - <sub>Tags: <code>2.4.1</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.wingpanel](https://github.com/elementary/wingpanel): [3.0.2 → HEAD](https://github.com/elementary/wingpanel/compare/3.0.2...HEAD)

- [x] [<code>Add support for Mutter 42 (#434)</code>](https://github.com/elementary/wingpanel/commit/b5e8f8b044a49da4621fdf044dfe21b1213edcde)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>command</code> <code>dependency</code></sub>
- [x] [<code>Update mutter-clutter-9.deps (#435)</code>](https://github.com/elementary/wingpanel/commit/0bb8396f7504feef6082a555123f1d733b4ed891)
- [x] [<code>Fallback to maximized style if Gala bus is unavailable (#445)</code>](https://github.com/elementary/wingpanel/commit/f186b6cabca403a62f97586fd0a5ce558dd0341e)
- [x] [<code>Styles: fix CSS syntax, remove extra class</code>](https://github.com/elementary/wingpanel/commit/6184480f94b466f78cae20bf2b134eb2ce545395)
- [x] [<code>IndicatorEntry: Remove hardcoded margin</code>](https://github.com/elementary/wingpanel/commit/e3d6123f422dc9d6d1417c7fbbb562246e883d4a)
- [x] [<code>Lib: Remove deprecated widgets (#450)</code>](https://github.com/elementary/wingpanel/commit/afa7e3cdbdacf0730961f015b045f037feccdc36)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>bin</code></sub>
- [x] [<code>Synchronize the .vapi with Gala (#453)</code>](https://github.com/elementary/wingpanel/commit/d12167bd77cec002af5222853b8919b14cd46e35)
- [x] [<code>Update wingpanel.appdata.xml.in</code>](https://github.com/elementary/wingpanel/commit/cdf7c19bce17e3854369ade4b54b6bb154b31e67)
- [x] [<code>Revert "Lib: Remove deprecated widgets" (#456)</code>](https://github.com/elementary/wingpanel/commit/a3c67cfbd4d94f52118f52cbf4dc18802561f85b)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>bin</code></sub>
- [x] [<code>Create CONTRIBUTING.md (#461)</code>](https://github.com/elementary/wingpanel/commit/db8591ae708d4f4bebea474e0b99166b8126e905)
- [x] [<code>Add support for Mutter 43 (#465)</code>](https://github.com/elementary/wingpanel/commit/60e344fdfe698a05c113cf664a7f5889c51cf603)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>command</code> <code>dependency</code></sub>
- [x] [<code>Listen to smooth scroll events (#466)</code>](https://github.com/elementary/wingpanel/commit/ea73ce711371b128763b6de23b86b27d6a7900d9)
- [x] [<code>Delete meson.build.rej</code>](https://github.com/elementary/wingpanel/commit/09d41831cddc18fb5a8b4c797596d6519a293e15)
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>Update wingpanel.appdata.xml.in</code>](https://github.com/elementary/wingpanel/commit/66483f8c9b0c149c634eb176603c167b7510cbcc)
- [x] [<code>Update release.yml</code>](https://github.com/elementary/wingpanel/commit/90a617b38d6de07e5c7f3f40c4efa71ee3556b44)
- [x] [<code>Meson: include Posix dep (#469)</code>](https://github.com/elementary/wingpanel/commit/8be50d17eb10458f89a6c5e029c81e6f3042c6f9)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>Update CI (#467)</code>](https://github.com/elementary/wingpanel/commit/bfac55a34ed6745a4845109f85b0713712177d2c)
- [x] [<code>Release 3.0.3 (#455)</code>](https://github.com/elementary/wingpanel/commit/f8b98a59d4d5cecd13f1c1a71f4700aeb006cc21)
  - <sub>Tags: <code>3.0.3</code></sub>
  - <sub>Files: <code>meson.build</code></sub>
