### ISSUE TITLE
Pantheon 7 updates 2022-10-21

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#11]
Just translations + appdata update + release commit:

- switchboard-plug-network
- switchboard-plug-onlineaccounts
- switchboard-plug-printers
- switchboard-plug-sharing

#### [pantheon.switchboard-plug-pantheon-shell](https://github.com/elementary/switchboard-plug-pantheon-shell): [6.3.0 → 6.3.1](https://github.com/elementary/switchboard-plug-pantheon-shell/compare/6.3.0...6.3.1)

- [x] [<code>Appearance: bind radios with mapping (#331)</code>](https://github.com/elementary/switchboard-plug-pantheon-shell/commit/03b094e5b77dd24b45037c04699a529bad8c2ea8)
- [x] [<code>Appearance: Reorder connection of signals (#334)</code>](https://github.com/elementary/switchboard-plug-pantheon-shell/commit/989831cf085889b06a2e667a7a4e7fe270fb2384)
- [x] [<code>Update io.elementary.switchboard.pantheon-shell.appdata.xml.in</code>](https://github.com/elementary/switchboard-plug-pantheon-shell/commit/c34a9196c4336b14b3968e5bd48902f6048c7bd7)
- [x] [<code>Update io.elementary.switchboard.pantheon-shell.appdata.xml.in</code>](https://github.com/elementary/switchboard-plug-pantheon-shell/commit/3852fc98f38028b032aecb801bdf3982c88dde08)
- [x] [<code>Release 6.3.1 (#337)</code>](https://github.com/elementary/switchboard-plug-pantheon-shell/commit/ca815e955786d3a8adbc773190c25d7fd752cd95)
  - <sub>Tags: <code>6.3.1</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.elementary-onboarding](https://github.com/elementary/onboarding): [7.0.0 → 7.0.1](https://github.com/elementary/onboarding/compare/7.0.0...7.0.1)
- [x] [<code>Bind number of days to setting (#176)</code>](https://github.com/elementary/onboarding/commit/288434a0c228afe5cc6b552ea7bb377b52c44850)
- [x] [<code>Update pot files</code>](https://github.com/elementary/onboarding/commit/8612cb52ec7eb23ab36717034c96d9bd2dfbb803)
- [x] [<code>ci: Use gettext action for Horus (#178)</code>](https://github.com/elementary/onboarding/commit/af6ad03f6203d698729c6cff335317383c18ba6d)
- [x] [<code>Update main.yml (#179)</code>](https://github.com/elementary/onboarding/commit/eb9bf5e78dafd806f016c24ded59b66950895fd4)
- [x] [<code>Use Gtk.Box for ImageLinkButton (#181)</code>](https://github.com/elementary/onboarding/commit/ec17c0213fc9efdc05d970f05a4c0decea0e33fb)
- [x] [<code>Update onboarding.appdata.xml.in</code>](https://github.com/elementary/onboarding/commit/150d5c277aa6ce516495af3a3a9d0c978addd8b0)
- [x] [<code>StyleView: use prefs-desktop-theme (#171)</code>](https://github.com/elementary/onboarding/commit/363c16cea4320976b67efa8b0d6e2f608da71840)
- [x] [<code>Release 7.0.1 (#183)</code>](https://github.com/elementary/onboarding/commit/de9771a90907fd36fa8f4c3e2f51c7f89ee3d094)
  - <sub>Tags: <code>7.0.1</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.pantheon-agent-geoclue2](https://github.com/elementary/pantheon-agent-geoclue2): [1.0.5 → 1.0.6](https://github.com/elementary/pantheon-agent-geoclue2/compare/1.0.5...1.0.6)
- [x] [<code>Geoclue2Dialog: Rewrite as Granite.MessageDialog (#42)</code>](https://github.com/elementary/pantheon-agent-geoclue2/commit/fadbea58fcabac9162e61f17f92da26f0a353252)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>Update io.elementary.desktop.agent-geoclue2.appdata.xml.in</code>](https://github.com/elementary/pantheon-agent-geoclue2/commit/8888ea75737fb705670e1def547781048b2185dd)
- [x] [<code>Release 1.0.6 (#55)</code>](https://github.com/elementary/pantheon-agent-geoclue2/commit/996250b8bb0743a339019dd474f2ef6aeedd724f)
  - <sub>Tags: <code>1.0.6</code></sub>
  - <sub>Files: <code>meson.build</code></sub>
