### ISSUE TITLE
pantheon.appcenter: 3.10.0 -> 4.0.0

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#12]
#### [pantheon.appcenter](https://github.com/elementary/appcenter): [3.10.0 → HEAD](https://github.com/elementary/appcenter/compare/3.10.0...HEAD)
- [x] [<code>AbstractView: Replace Stack with Deck (#1769)</code>](https://github.com/elementary/appcenter/commit/02dda381b16703183cd2220dc4efde0562af42f7)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>AppListView → SearchView (#1859)</code>](https://github.com/elementary/appcenter/commit/8c90e8161d11673ce1fd99137347475bc950623a)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>CategoryFlowBox: create Fun & Games (#1763)</code>](https://github.com/elementary/appcenter/commit/4a7a54290ec6330364dd8d844982340a15e7db82)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Provide default case for switches (#1858)</code>](https://github.com/elementary/appcenter/commit/d5115cbe59e831e71ee92f73535a25d3483b619f)
- [x] [<code>AppListUpdateView: move list population from InstalledView to here (#1860)</code>](https://github.com/elementary/appcenter/commit/3676d6687af2f097529dde88b8df2b28d740f636)
- [x] [<code>AppInfoView: Wrap package_name instead of ellipsize (#1867)</code>](https://github.com/elementary/appcenter/commit/e7e2cf65a719fba1a04023e9eca5fe7f5e509276)
- [x] [<code>Disallow scrolling with mouse wheel on screenshot carousel (#1868)</code>](https://github.com/elementary/appcenter/commit/dcfa199d626e1f4cd1261f01d9551e2485aa1acc)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>AppInfoView: Make screenshot carousel full page width (#1572)</code>](https://github.com/elementary/appcenter/commit/dc063d9d78e3d3dad2c7ef1f8cdab5e672f6bea4)
- [x] [<code>InstalledPackageRowGrid: release notes in a dialog (#1875)</code>](https://github.com/elementary/appcenter/commit/60ee3b16e659430a788e0820d8fe71a20d2c288b)
- [x] [<code>Homepage: remove dead currently_viewed_category (#1876)</code>](https://github.com/elementary/appcenter/commit/4be483dfef4952ed077608b3b5ae2e6fc9543f78)
- [x] [<code>AppInfoView: create accent provider per-view (#1872)</code>](https://github.com/elementary/appcenter/commit/3dd1fed5206ba246dff7a130b4d339f17fe817af)
- [x] [<code>UpgradeFailDialog: avoid crash from null GLib.Error (#1877)</code>](https://github.com/elementary/appcenter/commit/d11139fb5c3d068007c6551bddaef2fbd7c10a6a)
- [x] [<code>Remove dead NonCuratedWarningDialog.css (#1879)</code>](https://github.com/elementary/appcenter/commit/f09b3e781c2c2c1f48eb0eb48d65eff3f0c54598)
- [x] [<code>AppInfoView: Add background and caption to screenshots (#1878)</code>](https://github.com/elementary/appcenter/commit/690f9d82b50f1f6a42c8410d5ab1eb9b9dde926b)
- [x] [<code>MainWindow: Use icons for view mode switcher and center search (#1873)</code>](https://github.com/elementary/appcenter/commit/f3659bbb8b65744e8eb33ec19ba4eb4d17b8a94f)
- [x] [<code>Use a single Hdy.Deck for navigation (#1874)</code>](https://github.com/elementary/appcenter/commit/1822178ead75a2bd20d7a960d53add7c3f58d8e6)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Banner, AppInfoView: Use a single accent color, auto text color (#1880)</code>](https://github.com/elementary/appcenter/commit/3d74debafa295b3a77c9f0487e2391c919a46aac)
- [x] [<code>AppListUpdateView: Don't re-use cancellable (#1863)</code>](https://github.com/elementary/appcenter/commit/82c68ebc6cb03b6030336dba4707e4522b4fcdc9)
- [x] [<code>Package: get branding from appstream (#1883)</code>](https://github.com/elementary/appcenter/commit/94bb160d037280c3967fe7e7cce7e1801367d4de)
- [x] [<code>MainWindow: remove window position code (#1885)</code>](https://github.com/elementary/appcenter/commit/48cf13971387abaac6096a751570f5da0261a61c)
- [x] [<code>Use explicit properties (#1889)</code>](https://github.com/elementary/appcenter/commit/8a93dd26a6daa00751b42ff74f5b99a4a454dbf2)
- [x] [<code>CategoryView: highlight recently updated apps (#1856)</code>](https://github.com/elementary/appcenter/commit/b94341d148dd932f1d20a8a7207b44f62d41aea1)
- [x] [<code>AppInfoView: use a flowbox for links (#1884)</code>](https://github.com/elementary/appcenter/commit/085f930e5e459f4cbae7ddb1bd415b17cb82dbae)
- [x] [<code>Move NetworkInfoBar to MainWindow (#1888)</code>](https://github.com/elementary/appcenter/commit/fb547f0e6ff1d017cbef7d1b7768ea0d4d3d440f)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Package: expose ComponentKind as property (#1887)</code>](https://github.com/elementary/appcenter/commit/0b1670783af442ca4910938398c9c47d11fe6323)
- [x] [<code>meson: require appstream >= 0.15.2 (#1893)</code>](https://github.com/elementary/appcenter/commit/886700fa279f6b017976b233ed8a6e1d85a39438)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>Move Deck to MainWindow (#1882)</code>](https://github.com/elementary/appcenter/commit/e90804998193ec4d8dc9cb1d8e5f1520ca16b88f)
- [x] [<code>Replace Gtk.Grid with Gtk.Box (#1886)</code>](https://github.com/elementary/appcenter/commit/ba3ea3be80ddf65deeb5df710cfd32f721191e5d)
- [x] [<code>Package: use AppCenter origin in should_pay (#1892)</code>](https://github.com/elementary/appcenter/commit/99b4d36b826bbe4501dc5085a7d4858805703600)
- [x] [<code>Package: Remove should_nag_update (#1891)</code>](https://github.com/elementary/appcenter/commit/fc5b0428113ae07b74fecd5f5c67f189060fdbc5)
- [x] [<code>CategoryView: don't subclass Gtk.FlowBox (#1895)</code>](https://github.com/elementary/appcenter/commit/69d60750fb5f6acc62aeee466cf9fc32181ff23f)
- [x] [<code>Homepage: absorb CategoryFlowBox (#1898)</code>](https://github.com/elementary/appcenter/commit/be58ed869c1084c51c557afe9c5ba27aedc3d5f7)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>SharePopover: code style and DRY (#1900)</code>](https://github.com/elementary/appcenter/commit/1e057a307cb7e5962ebb379c6a69a3f4d042ba3b)
- [x] [<code>AppInfoView: absorb ReleaseListBox (#1899)</code>](https://github.com/elementary/appcenter/commit/035b22d27d627d5077f25f8f70538066dcb4c2c5)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>StripeDialog: code style and boxes (#1905)</code>](https://github.com/elementary/appcenter/commit/d9eaf0fc2b456cc1f0cffde05fe649f07175301a)
- [x] [<code>DBusServer: connect to uninstall_confirm response</code>](https://github.com/elementary/appcenter/commit/de52de653c13636da1e69e4ae2dfe7ed31deb225)
- [x] [<code>Application: installfaildialog present</code>](https://github.com/elementary/appcenter/commit/d65217b051daa37284168695092f95f313910839)
- [x] [<code>InstalledPackageRowGrid: ReleasesDialog subclass Granite.Dialog</code>](https://github.com/elementary/appcenter/commit/1d4b5676594046ed3ef89bd212d15ac24fa6c16c)
- [x] [<code>MainWindow: message_dialog.present</code>](https://github.com/elementary/appcenter/commit/65a6cdd2f13d6ae24b6a4b466db04be95dea48d4)
- [x] [<code>Arrow.css: fix blurry border (#1902)</code>](https://github.com/elementary/appcenter/commit/d76619b807cab89770a6c90d81610119fcbebd10)
- [x] [<code>Application: use active_window (#1903)</code>](https://github.com/elementary/appcenter/commit/6543b352114e35f939b1e9e902578b199389ef50)
- [x] [<code>CategoryView: change append to add_package (#1908)</code>](https://github.com/elementary/appcenter/commit/8d913ad18d76d3b1758e4adc1df349b3fcfb5d18)
- [x] [<code>AbstractAppList: Remove list.add connect (#1909)</code>](https://github.com/elementary/appcenter/commit/85bf6b9a9d623287571ce97d646db8e1342c6493)
- [x] [<code>Homepage categories (#1907)</code>](https://github.com/elementary/appcenter/commit/8ca31d592efeea38f0c49136d02ec91a5c9c73bb)
- [x] [<code>Move remove_package from AbstractAppList to AppListUpdateView (#1910)</code>](https://github.com/elementary/appcenter/commit/3ac08f63a1f40cdacac8e4bbe06204c8303eb37e)
- [x] [<code>AbstractAppList: Remove sort func (#1911)</code>](https://github.com/elementary/appcenter/commit/a33da427f6a3b5fa6a63a2d171f8a996c21864c7)
- [x] [<code>AbstractAppList: Remove add_package (#1913)</code>](https://github.com/elementary/appcenter/commit/6750ad057469adc1ad3bd75a987213d3eb270c37)
- [x] [<code>Package: assign icons for more componentkinds (#1914)</code>](https://github.com/elementary/appcenter/commit/8ab255da3fdd16214c68acd94eb133e5e8262ed5)
- [x] [<code>Move get_packages from AbstractAppList to AppListUpdateView (#1912)</code>](https://github.com/elementary/appcenter/commit/fcf693cfe76f424cf4e3ff0c1cfb8dcc2fb3bd2d)
- [x] [<code>AbstractAppList: Remove redundant package_changing (#1915)</code>](https://github.com/elementary/appcenter/commit/b7e42afd50ca8d2c6ecc407123fdc1e221339205)
- [x] [<code>AppListUpdateView: Fix typo in package row compare (#1917)</code>](https://github.com/elementary/appcenter/commit/7ba182a52596c272ebe3497c70beeb2882ef20b1)
- [x] [<code>Remove AbstractAppList (#1916)</code>](https://github.com/elementary/appcenter/commit/b2b164a83e199b39dc963d266bc0b4a313142ad9)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Show current job type in overlaybar (#1919)</code>](https://github.com/elementary/appcenter/commit/0a272694ec363c8d503bcf22ce7ccfc3bf52ec25)
- [x] [<code>MainWindow: don't rely selected_package (#1918)</code>](https://github.com/elementary/appcenter/commit/d06b5cf1525de827e71de3418958b517f02bcfdc)
- [x] [<code>AppListUpdateView: make update all header sticky (#1921)</code>](https://github.com/elementary/appcenter/commit/d52bc1acdd89a0fe8f2a3469a665e384fbf9b993)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>ReleaseRow: cleanup and design update</code>](https://github.com/elementary/appcenter/commit/077a1250caba0baf90c94326956dacf53ff08d59)
- [x] [<code>AppInfoView: get newest releases in this class</code>](https://github.com/elementary/appcenter/commit/a75b72d9f27eab4f17ca5ee6b53e2e849c11782f)
- [x] [<code>Remove redundant null check</code>](https://github.com/elementary/appcenter/commit/d31f59eea5c85838efff339b901f0c7aab2b6883)
- [x] [<code>ReleaseRow: support issues tag (#1931)</code>](https://github.com/elementary/appcenter/commit/4f0756c59b7b2ffb01f552b443d9691d1a3f5140)
- [x] [<code>UpdateManager: count updates size, flatpak, unpaid (#1924)</code>](https://github.com/elementary/appcenter/commit/cf8af4baa7937a8aad9160df93f6a57e71898228)
- [x] [<code>Update pot files</code>](https://github.com/elementary/appcenter/commit/236bc1d5ebdd31e516c813f119f0ea9f17fecb86)
- [x] [<code>gettext: Set the next version as action runner</code>](https://github.com/elementary/appcenter/commit/ba26ff55da8026c95525450551200418c36a108a)
- [x] [<code>Revert "gettext: Set the next version as action runner"</code>](https://github.com/elementary/appcenter/commit/981ab2837141198594b986fbbd03fe174907449d)
- [x] [<code>gettext: Use next branch by default</code>](https://github.com/elementary/appcenter/commit/9af40937b2979336fbd01c4d791e51472d35c259)
- [x] [<code>gettext: use ubuntu 22.04</code>](https://github.com/elementary/appcenter/commit/9ba8f3d4ad864ef28fcc75f3191b59d07125c463)
- [x] [<code>fix: Segfault from error message being freed in dialogs (#1936)</code>](https://github.com/elementary/appcenter/commit/da68394052c8a04135aff02ea24e53933b55abfc)
- [x] [<code>Fix CI (#1937)</code>](https://github.com/elementary/appcenter/commit/d6fb2444bced9b0bde27fe774ad2c24c13fc8d62)
- [x] [<code>AppData: add 4.0.0 release notes (#1938)</code>](https://github.com/elementary/appcenter/commit/494355ca237b1ccbaa4c11932102e10531cdf3dc)
- [x] [<code>UpgradeFailDialog: offer refresh option (#1942)</code>](https://github.com/elementary/appcenter/commit/a69a7756cdd73c823d00a64d755343180055de72)
- [x] [<code>Release 4.0.0 (#1939)</code>](https://github.com/elementary/appcenter/commit/708306914ca12a7db14ed3e59510c787e4f398f8)
  - <sub>Tags: <code>4.0.0</code></sub>
