### ISSUE TITLE
cinnamon.cinnamon-common: 5.4.12 -> 5.6.1

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#14]
#### [cinnamon.cinnamon-common](https://github.com/linuxmint/cinnamon): [5.4.12 → HEAD](https://github.com/linuxmint/cinnamon/compare/5.4.12...HEAD)

- [x] [<code>workspacesView.js: Disconnect swipe handlers during destroy</code>](https://github.com/linuxmint/cinnamon/commit/59844f49691f1e723f08ea40d7aaaea93acd691b)
- [x] [<code>Update issue templates.</code>](https://github.com/linuxmint/cinnamon/commit/befde43be12b4294ec1a7b52ae5b3bc285ee4dfc)
- [x] [<code>messageTray.js: Don't assume the primary monitor is at index 0.</code>](https://github.com/linuxmint/cinnamon/commit/0219123db73a1d3a1d74b27a54fbe0f1407b5ae9)
- [x] [<code>modalDialog.js: Don't assume monitor 0 is the primary.</code>](https://github.com/linuxmint/cinnamon/commit/c209bab2cf58c663e92aaffcc565b38bb42a1f6b)
- [x] [<code>remove trailing semicolons</code>](https://github.com/linuxmint/cinnamon/commit/cc90cd27cf2407a8e8486ed934f3edb7af4a3144)
- [x] [<code>remove trailing semicolons</code>](https://github.com/linuxmint/cinnamon/commit/9559f0da0eda1d73ef0010733185b66daa6cabd8)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Fix inconsistent keyboard navigation in the Scale View and in the Expo View. (#11098)</code>](https://github.com/linuxmint/cinnamon/commit/f1e9887a81e41ceb5cf6a53782f1727b7cd66e87)
- [x] [<code>fix variable name (#11152)</code>](https://github.com/linuxmint/cinnamon/commit/b90b06ae1f41f67dee939cfb0cc026b7b5744b63)
- [x] [<code>gwl: don't pass the wrong arguments to windowRemoved.</code>](https://github.com/linuxmint/cinnamon/commit/1f56454f0244049a1734d01ecc607f2a59465ee5)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>expo: Update the window's starting position when an update is</code>](https://github.com/linuxmint/cinnamon/commit/ac47ff37c120b506ba67375e0334764bb8d8e14d)
- [x] [<code>overrides: Make MetaWindowActor.get_workspace always return an</code>](https://github.com/linuxmint/cinnamon/commit/b207debc9f4344307c7246cc1eb0d7f71c3b0743)
- [x] [<code>Use github instead of circleci.</code>](https://github.com/linuxmint/cinnamon/commit/95aa8f686472b4e7b22b9080bf896842e74a583f)
  - <sub>Keywords: <code>command</code></sub>
- [x] [<code>workflow: Fix dependency line.. maybe.</code>](https://github.com/linuxmint/cinnamon/commit/250d83d80a1b0104b0d5649fbda38cff9f133ddd)
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>workflow: Go back to folded style.</code>](https://github.com/linuxmint/cinnamon/commit/04c3a212cf60b2ee901a79977c39b8cf95729fc4)
- [x] [<code>settings: Make use of cinnamon-driver-manager shortcut</code>](https://github.com/linuxmint/cinnamon/commit/6c76516c9e107f0ec0c0e24fa7722350c0c2dcfc)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>gwl: fix reload dragging pinned apps when group windows setting is disabled (#11191)</code>](https://github.com/linuxmint/cinnamon/commit/087efed237d720a0555ad6d055ab0e188e591aab)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>replace deprecated use of GObject.SIGNAL_RUN_FIRST by GObject.SignalFlags.RUN_FIRST (#11128)</code>](https://github.com/linuxmint/cinnamon/commit/9ace2c4416b131f7d35728d168f8d91d12978e3c)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_windows.py: Properly import CDesktopEnums (#10844)</code>](https://github.com/linuxmint/cinnamon/commit/3d4e67e952adf50ed1549027b05f32fdf98cd62f)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_themes.py: Don't print an error if metadata.json is missing</code>](https://github.com/linuxmint/cinnamon/commit/dabf4d31aab341714061541383bac77343077aab)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>cs_themes.py: Separate light/dark/darker themes</code>](https://github.com/linuxmint/cinnamon/commit/71351625223b98f88e54e25f733c81f436d1f0c5)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Add new cornerbar applet</code>](https://github.com/linuxmint/cinnamon/commit/ce770e3749d1f480a55825cf3ffa6d2a598fd6c1)
  - <sub>Keywords: <code>usr</code> <code>dependency</code></sub>
- [x] [<code>Panel: Replace show-desktop with cornerbar</code>](https://github.com/linuxmint/cinnamon/commit/cd47f9aef5c383a108c5f77098d3c602b2e0bc86)
- [x] [<code>l10n: Update POT</code>](https://github.com/linuxmint/cinnamon/commit/58d3c7935ae0494fe753ca3d33091fb377ff80e8)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>corner-bar: Don't track_hover on the bar actor.</code>](https://github.com/linuxmint/cinnamon/commit/b60a8f9ed008ecdd0a41e25b6fc41d0cce3d92fc)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>desklets: Allow desklets to be locked in place.</code>](https://github.com/linuxmint/cinnamon/commit/cb3a06df46889e5b6bbaa1c82ed060e0169c2979)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>remove trailing semicolons</code>](https://github.com/linuxmint/cinnamon/commit/24d660af46ed3b7cdef9980f5991de466645a8e6)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>cs-info: Add system icon (#11090)</code>](https://github.com/linuxmint/cinnamon/commit/30a8144c7ab832cd3b26198561ae5f711fcc802c)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_info: Keep system image a reasonable size.</code>](https://github.com/linuxmint/cinnamon/commit/0b32933489c796ffc468f8160ec9e97fbe7a4c21)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>debian/control: Add missing dependency.</code>](https://github.com/linuxmint/cinnamon/commit/106ac24f8fe788d55c035c812c6fc0635c231e4e)
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>data/icons/meson.build: Silence a build warning.</code>](https://github.com/linuxmint/cinnamon/commit/4229af950cbacf3a33e48c0300fd8f75bc9d5186)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Move spices download cache to `XDG_CACHE_HOME` directory (#11176)</code>](https://github.com/linuxmint/cinnamon/commit/74c26ab74e7ae0a46c134c62ac2e537d4ec427e6)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>cs_keyboard: Add an entry to allow type-to-search shortcut names.</code>](https://github.com/linuxmint/cinnamon/commit/75a53a803edffabcab8177f16944a9055a33e7f4)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_themes: Don't require themes to support Gtk 2 any longer</code>](https://github.com/linuxmint/cinnamon/commit/4c54812ce6461eab5e7d382dbee129f3b4db0d46)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>windowMenu.js: Implement mnemonic accelerators.</code>](https://github.com/linuxmint/cinnamon/commit/325eeb1f332d82b45f33392040213a2d3c73c1ed)
- [x] [<code>makepot: Collect comments from js files.</code>](https://github.com/linuxmint/cinnamon/commit/e471ac1aa376a35f8f14a96e0b8f7ca3f09401c7)
  - <sub>Keywords: <code>usr</code> <code>exec</code></sub>
- [x] [<code>harvester.py: cache_folder should be a pathlib.Path.</code>](https://github.com/linuxmint/cinnamon/commit/7c884631de90802b1a74f55c0d05f6af4c6bcd7c)
- [x] [<code>windowMenu.js: Never allow more than one menu at a time.</code>](https://github.com/linuxmint/cinnamon/commit/e49a997d60c23921eec879ca3cb44ba2177be39d)
- [x] [<code>appSwitcher.js: Account for alt-tab reverse actions in the window.</code>](https://github.com/linuxmint/cinnamon/commit/af3361847cb9a0944a7b7ac15299dab918e56a9f)
- [x] [<code>cs_keyboard: Add missing switch-panels and switch-panels-backward</code>](https://github.com/linuxmint/cinnamon/commit/1877d2feead01506dfb2c6615d8514c65b4ba27b)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Support multiple key bindings for 'locate-pointer-key' (#11143)</code>](https://github.com/linuxmint/cinnamon/commit/2a42b80a4f106de3ea3f3ce4a8d3695d96fb224c)
- [x] [<code>cs_info: There should be no image set by default.</code>](https://github.com/linuxmint/cinnamon/commit/f8c09b013cf0938df6ad2825598a75a81992c6f6)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs-info: Don't fail with the default system-icon-path value (#11245)</code>](https://github.com/linuxmint/cinnamon/commit/be4ed1632ef4f640b5e35c087fe8279b18c1d6a9)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Add support for key bindings to Inhibit Applet</code>](https://github.com/linuxmint/cinnamon/commit/4a921f45d80d461290f01bb0ecead8db5a5dbff0)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Cleanup whitespace</code>](https://github.com/linuxmint/cinnamon/commit/18d2377f8839c842232e096570d7b25a46953f39)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>replace equality None check with identity None check</code>](https://github.com/linuxmint/cinnamon/commit/dd334a6a05a626fca2ff401ec3bb48f6570c8eca)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>fix: Actually use `XDG_DATA_HOME` to store themes and icons instead of home (#11175)</code>](https://github.com/linuxmint/cinnamon/commit/0fc32e2047ec9e451034ebd87a50caeb240eb6c4)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>Use XDG_CONFIG_HOME to store background config files instead of .cinnamon (#11177)</code>](https://github.com/linuxmint/cinnamon/commit/c0986743cad1f3daa39425b5a125b22d7b6f1daa)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Use XDG_CONFIG_HOME to primarily store spices configs in (#11182)</code>](https://github.com/linuxmint/cinnamon/commit/f3729147cb652b2e13969a76fb861a276e602ee3)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>fix: use XDG_DATA_HOME to store custom launchers, also fix launcher desklet (#11185)</code>](https://github.com/linuxmint/cinnamon/commit/844493a8279bb326c4ff79490d8f39c0d539960d)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Use `XDG_STATE_HOME` for logfiles instead of `~/.cinnamon` (#11186)</code>](https://github.com/linuxmint/cinnamon/commit/323b5aa3f3070168956c46cbb0ba140fe66215e8)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>remove unused imports harvester.py</code>](https://github.com/linuxmint/cinnamon/commit/9150b4d0299dc3a2fc65120baee787b7c8a1a533)
- [x] [<code>remove unused imports updates.py</code>](https://github.com/linuxmint/cinnamon/commit/75af79b7770abc057478083308655e4ba0a672ee)
- [x] [<code>use @staticmethod in Spices.py (#11257)</code>](https://github.com/linuxmint/cinnamon/commit/86cda6c584190830722d7f08a1b22ddc10786778)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>fix python docstring style (#11258)</code>](https://github.com/linuxmint/cinnamon/commit/4c5deb0a2bd152badee72935122d4d1154874590)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>simplify boolean check in cs_default</code>](https://github.com/linuxmint/cinnamon/commit/7669cbecdbf16ae26ca78e1153f03cdcff08cfef)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>remove redundant parentheses (#11259)</code>](https://github.com/linuxmint/cinnamon/commit/50a88f5b0fcf0f03a349b554ddd359e5bfed9a6d)
  - <sub>Keywords: <code>bin</code> <code>usr</code> <code>exec</code></sub>
- [x] [<code>Use a custom actor for the uiGroup.</code>](https://github.com/linuxmint/cinnamon/commit/6577feb68ab42fd651617295066269475a25138d)
- [x] [<code>cs_backgrounds: Use font-size instead of font-scale to reduce the</code>](https://github.com/linuxmint/cinnamon/commit/60fde9403e5ece1932b031a9fdbabd9ef278cf5c)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>build: Fix some hardcode path issues (#11244)</code>](https://github.com/linuxmint/cinnamon/commit/b881ad787c6d59554b69bc61ca8f4a7f51827d73)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>bin</code> <code>usr</code> <code>command</code> <code>exec</code> <code>dependency</code></sub>
- [x] [<code>replace equality None check with identity None check</code>](https://github.com/linuxmint/cinnamon/commit/f195cf1d7bdcd3e1ef29d47d2a1dfe8e93f3b777)
  - <sub>Keywords: <code>bin</code> <code>usr</code></sub>
- [x] [<code>removed unused variable check-js</code>](https://github.com/linuxmint/cinnamon/commit/d0982692983bd7d304b0f919578dd978d8047cf5)
- [x] [<code>GWL: Move nemo shortcut to the left</code>](https://github.com/linuxmint/cinnamon/commit/a7588374bb099efe16be4b0db90478306c6d67e1)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Add a setting for notification duration (#11202)</code>](https://github.com/linuxmint/cinnamon/commit/b2e1490fc8d92e3d4cdb36d4f4fd90faa5cc471b)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Rename "Preferences" to "Applet preferences" in applets where it might be confusing (#11216)</code>](https://github.com/linuxmint/cinnamon/commit/f9267d558335082f9d11c1b9d03a9cc4ec8568a5)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Categorize default applications (#11287)</code>](https://github.com/linuxmint/cinnamon/commit/89c7722b2e90f6fd01bf6d5bf1aa91d55075c38c)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_default: Fix a typo, and set a default height to prevent the</code>](https://github.com/linuxmint/cinnamon/commit/efdd025f9500dc7e1f6b8598511dc04a1b402c13)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Add key bindings to move window to workspace up/down (#11264)</code>](https://github.com/linuxmint/cinnamon/commit/b1893114ad1b5e9d1fae8e2bf976e58b38fef0cd)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_keyboard: Improve a few keybinding descriptions.</code>](https://github.com/linuxmint/cinnamon/commit/6a7f3a637e6792f872c93be0b55bcfe85cf25ed0)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>The middle click toggles the sound and places the microphone in the same state. #11255 (#11256)</code>](https://github.com/linuxmint/cinnamon/commit/c575a29d9d96735056412d0b09feb7f5fdf3512a)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>cs_default.py: Add entry for terminal exec-arg</code>](https://github.com/linuxmint/cinnamon/commit/d6d8f3453c847e1e59803ea564ebedc5c1b0f096)
  - <sub>Keywords: <code>usr</code> <code>command</code> <code>exec</code></sub>
- [x] [<code>Improve presentation of terminal args.</code>](https://github.com/linuxmint/cinnamon/commit/eca601febd67536863548f5de23743bb0e23a969)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>layout.js: Actually change actor visibility on fullscreen monitors.</code>](https://github.com/linuxmint/cinnamon/commit/1deb0ff03652f0613a564e86c8090f7f007eb970)
- [x] [<code>Restore set_skip_paint method for the uiGroup.</code>](https://github.com/linuxmint/cinnamon/commit/c7ecb6dfeeaaada5877ae2136778b9b96af50a40)
- [x] [<code>appletManager.js: Fix typo.</code>](https://github.com/linuxmint/cinnamon/commit/c8ed2ed330871b312275145f3364da41762f92bb)
- [x] [<code>layout.js: Fix picking in fullscreen.</code>](https://github.com/linuxmint/cinnamon/commit/736b2e1452b5164965cf9d129063a08c6d7952e3)
- [x] [<code>python: optimize lists (#11281)</code>](https://github.com/linuxmint/cinnamon/commit/9d4543bfe319944d821c819bd20dd6ba80f0810a)
  - <sub>Keywords: <code>usr</code></sub>
- [x] [<code>Depend on libcjs0</code>](https://github.com/linuxmint/cinnamon/commit/3494866f0691f4e4a0cceb92656a1d69723ce3a2)
  - <sub>Tags: <code>master.lmde5</code> <code>master.mint21</code></sub>
