### ISSUE TITLE
Pantheon 7 updates 2023-01-25

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#16]
#### [pantheon.appcenter](https://github.com/elementary/appcenter): [4.0.0 → HEAD](https://github.com/elementary/appcenter/compare/4.0.0...HEAD)

- [x] [<code>Update meson.build</code>](https://github.com/elementary/appcenter/commit/0d206ac564becd7646d408003d3fa8e9663a86fa)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>PackageKitBackend: resolve addons in appstream pool (#1946)</code>](https://github.com/elementary/appcenter/commit/ebf4c36f64d62158a18708adfeb2440589cfba8e)
- [x] [<code>po/remove author by request</code>](https://github.com/elementary/appcenter/commit/02852ac68282d53122ed292d371819558cdb5b11)
- [x] [<code>Gresource: add more category icons (#1948)</code>](https://github.com/elementary/appcenter/commit/3bb4adfa95fe419f82da544756647c83592067d2)
- [x] [<code>Fix visual issues with category icons (#1954)</code>](https://github.com/elementary/appcenter/commit/09edce06723182ea2f25a3f3e21cd4eb699b1cbd)
- [x] [<code>Flatpak Runtimes (#1956)</code>](https://github.com/elementary/appcenter/commit/345d5dc0dc410badbdf64bb0756250d920d1b8c1)
- [x] [<code>Size information for Runtime Updates (#1957)</code>](https://github.com/elementary/appcenter/commit/aea1c13f6f19a51e6d9b5ea10ae7f23f0ffa0b6c)
- [x] [<code>Install PackageKit based Operating System Updates as Offline Updates (#1943)</code>](https://github.com/elementary/appcenter/commit/73ac7e626b241b0162a7c99f5ef7ffcf4c10588e)
- [x] [<code>Pretty output Flatpak package origins (#1962)</code>](https://github.com/elementary/appcenter/commit/089144d6c8137d64f56223f5c75c02e22f34e3f3)
- [x] [<code>Warn running in Demo Mode (#1963)</code>](https://github.com/elementary/appcenter/commit/4c755a41ddd155f03f9b2d94d184f7c8571c88c7)
- [x] [<code>Show Operating System Updates and Runtime Updates only if available (#1960)</code>](https://github.com/elementary/appcenter/commit/8cb5b1d4289ca82d8fb48efb011dab25be29463b)
- [x] [<code>Make loading updates async from main AppCenter window (#1964)</code>](https://github.com/elementary/appcenter/commit/e5dbee5d21dc038cb9d3bf1070e8edfe520a42bf)
- [x] [<code>actions/checkout@v3 (#1966)</code>](https://github.com/elementary/appcenter/commit/39fdabf898ad9ff8ce1f0410328dab97859b25c3)
- [x] [<code>Update io.elementary.appcenter.appdata.xml.in (#1967)</code>](https://github.com/elementary/appcenter/commit/a2bd85dd34ca9f7f0238e5d5c914759269074571)
- [x] [<code>Gettext: install git (#1968)</code>](https://github.com/elementary/appcenter/commit/16be4364160efa9f2ba40608c2870cce2f9032ef)
- [x] [<code>Update gettext.yml</code>](https://github.com/elementary/appcenter/commit/0c111cf69aea6c243677b4a37cb7f30b970a8401)
- [x] [<code>Update gettext.yml</code>](https://github.com/elementary/appcenter/commit/5ba8a75fb5aef1f10d5efa6acea580a84a1bfbc5)
- [x] [<code>Gresource: mark OARS icons as scalable, scale all to 32px (#1970)</code>](https://github.com/elementary/appcenter/commit/2e714424bd7e912d6af85372dd45fca4509f8f25)
- [x] [<code>Update screenshots</code>](https://github.com/elementary/appcenter/commit/6d937a051c284f4d37f384b507a439f0f90fe3ca)
- [x] [<code>Metainfo Improvements (#1972)</code>](https://github.com/elementary/appcenter/commit/ecb2fec8f3aa6806b41af12670cdfaba6a9757a3)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Skip clearing components of visible category view (#1973)</code>](https://github.com/elementary/appcenter/commit/bb6a770ca20367379955c91b7cccd7298f7301ad)
- [x] [<code>Release 7.0.0 (#1971)</code>](https://github.com/elementary/appcenter/commit/2655456b71d6cfbbb69c5ca5352a842d62c7636a)
  - <sub>Tags: <code>7.0.0</code></sub>
  - <sub>Files: <code>meson.build</code></sub>

#### [pantheon.elementary-code](https://github.com/elementary/code): [6.2.0 → HEAD](https://github.com/elementary/code/compare/6.2.0...HEAD)

- [x] [<code>Fix compiler warnings (#1056)</code>](https://github.com/elementary/code/commit/78c08213c3351241238b7c58870a0c1d9e4587ac)
- [x] [<code>added code to keywords (#1195)</code>](https://github.com/elementary/code/commit/8d9370ae67e719ba697024a3aa75416e061da831)
- [x] [<code>Fix DnD (#1194)</code>](https://github.com/elementary/code/commit/1ed7b590768ea9cb5b4658e27d9dc7ac224442ae)
- [x] [<code>Add flatpak build files to .gitignore (#1197)</code>](https://github.com/elementary/code/commit/8f4d1ae1fb4b579b9c811c0e855d4ea855b2914f)
- [x] [<code>Ensure tab toggle label is always correct (#1145)</code>](https://github.com/elementary/code/commit/95f037b724acc7605e749073e6b440bb93495e72)
- [x] [<code>Add follow system style switch (#1202)</code>](https://github.com/elementary/code/commit/94fa089ceb8669847041ca73e3720127fc0f9e40)
- [x] [<code>Explicitly handle missing cases (#1199)</code>](https://github.com/elementary/code/commit/04ad197a43626ce829387aa5c22de31171a59d0e)
- [x] [<code>Update io.elementary.code.appdata.xml.in</code>](https://github.com/elementary/code/commit/e5322f1fceb11bc6ce042eeff59788fab4fb86cf)
- [x] [<code>Remove unused properties (#1205)</code>](https://github.com/elementary/code/commit/c6750d9721007dc432f5b84f217e52128104757b)
- [x] [<code>Change key to trigger rebuild completion word list (#1149)</code>](https://github.com/elementary/code/commit/17c0c835a207c10948560f5369d91cb13d033f51)
- [x] [<code>Global search selected (#1049)</code>](https://github.com/elementary/code/commit/8e1453442375226cb4a3fc5a92de8190d4a60dbd)
- [x] [<code>Move strip trailing whitespace into main code; remove plugin (#1151)</code>](https://github.com/elementary/code/commit/c5908dbdb2bc1aa3391dfb0f1e5c5eeb05b45e20)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>command</code></sub>
- [x] [<code>Fix meson warning for run_command (#1207)</code>](https://github.com/elementary/code/commit/0410f335cc516510a9f3d00895d886e15009361a)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Add custom elementary syntax styles (#1076)</code>](https://github.com/elementary/code/commit/b5d84a12700d8a8761b5139c3be0df93643f84ac)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>command</code></sub>
- [x] [<code>Hide non-active documents when project manually chosen (#1114)</code>](https://github.com/elementary/code/commit/91eebdbc5d916c73b3f02545aece233c37cb994f)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Show symbol outline pane on right of document (#1048)</code>](https://github.com/elementary/code/commit/9cf6b746c3e0e00bc97b8b3bc74f11461c056b3b)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>command</code> <code>subprocess</code> <code>dependency</code></sub>
- [x] [<code>POTFILES: Remove strip-trailing plugin</code>](https://github.com/elementary/code/commit/96d6fb92b25d3e4f41cdb1b6da002b166382b662)
- [x] [<code>POTFILES: Update symbol outline paths</code>](https://github.com/elementary/code/commit/a7db70bdcbfa28ddb97951375241a0de7dd83198)
- [x] [<code>plugins POTFILES: Remove strip-trailing and outline</code>](https://github.com/elementary/code/commit/58276be9b8ca4b52273ddd1abcbd8fb0390d5da7)
- [x] [<code>ProjectFolderItem: Fix wrong ngettext syntax</code>](https://github.com/elementary/code/commit/096e158652f159bc107513c465f6a2d04828fa57)
- [x] [<code>Redesign app icon as a tile (#1211)</code>](https://github.com/elementary/code/commit/1d4907070dbbe45eedaf714f83f36a4fad944eb1)
  - <sub>Files: <code>meson.build</code></sub>
- [x] [<code>Put the ProjectChooserButton inside the sidebar (#1217)</code>](https://github.com/elementary/code/commit/d7e592fc9e81ff26591edbda25a48731b42cc8bf)
- [x] [<code>HeaderBar: put find actions in menu (#1219)</code>](https://github.com/elementary/code/commit/0758bb24f11dc1d6c932ee7cfb5a903ddcbf5d85)
- [x] [<code>EditorConfig plugin overrides global settings for indent width and style (#1204)</code>](https://github.com/elementary/code/commit/895cccdb9f1174b22fee3eb643ed7a9f2a1338b0)
- [x] [<code>Make sidebar pane the toplevel container (#1218)</code>](https://github.com/elementary/code/commit/c721a7d82e5e7fc765f39eb7e54c8f75668b8821)
- [x] [<code>Use elementary styles when following system style (#1222)</code>](https://github.com/elementary/code/commit/beca59ffb1ee548d6710c88e441e85ed4b239b4d)
- [x] [<code>Change panel menu items to linkbutton (#1223)</code>](https://github.com/elementary/code/commit/3eb601c72503df55ff00d9c58fa0bdfdb2da880c)
- [x] [<code>FormatBar: use SwitchModelButton in tab popover (#1227)</code>](https://github.com/elementary/code/commit/6515f86dadee738b4ca12cc992faf82b4807111b)
- [x] [<code>Move Terminal to core (#1225)</code>](https://github.com/elementary/code/commit/7fe5ce87539af2058136371338ce9621a40713c6)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>command</code> <code>dependency</code> <code>org.gnome.desktop</code></sub>
- [x] [<code>Headerbar: remove sep before Revert (#1230)</code>](https://github.com/elementary/code/commit/fb130afbb067eff593495cc4ad85492b29dd37f6)
- [x] [<code>Update POTFILES</code>](https://github.com/elementary/code/commit/e250a2980da9c67d5e702dc6e975a378b2ec8648)
- [x] [<code>Update POTFILES</code>](https://github.com/elementary/code/commit/3ec3a349c8d7c6237fc833284df94544d3c0f0c5)
- [x] [<code>Update screenshots</code>](https://github.com/elementary/code/commit/8b84d7bfd3b987cbda8e329e41b86729dea6a3c7)
- [x] [<code>FormatBar: use menubuttons instead of ToggleButtons (#1231)</code>](https://github.com/elementary/code/commit/e6804c5d9f42b9c60edbf4e4fd9da911fc89dd7a)
- [x] [<code>Sidebar: Remove minimum width (#1233)</code>](https://github.com/elementary/code/commit/f13690def5c7227e79cb18c2bb4bc645d9404891)
- [x] [<code>GSchema: follow system style by default (#1235)</code>](https://github.com/elementary/code/commit/645fcdad9c740a653b0f02f3a960dd84cdfdc1a6)
- [x] [<code>Only restore documents for first window. (#1239)</code>](https://github.com/elementary/code/commit/c607a1388e7ee78aa11077fcefb6b543d37cc44c)
- [x] [<code>Do not add duplicate project (#1238)</code>](https://github.com/elementary/code/commit/cdc1c60c569fb2cbe2a31d8a1dd0cef8dfcf0121)
- [x] [<code>Update ci.yml (#1242)</code>](https://github.com/elementary/code/commit/fb973a7d1e95b9b5c28cecb2527b8acb1cdf1135)
- [x] [<code>FormatBar: Set sensitivity of affected items, fix binding (#1236)</code>](https://github.com/elementary/code/commit/63167ea82efe387f1622d7bcf0e22ac140de1647)
- [x] [<code>PluginManager: Remove unused hooks (#1240)</code>](https://github.com/elementary/code/commit/a1674c94f35c6b7224fec6f400f20d40dd5c4e48)
- [x] [<code>Make Control-Scroll zooming controllable (#1245)</code>](https://github.com/elementary/code/commit/5ee9bd5d5ed7bdc6c04d559d101a07f99ab393a4)
- [x] [<code>Metainfo improvements (#1241)</code>](https://github.com/elementary/code/commit/724d44d47c53735658be7912526d19345d0a6b2d)
  - <sub>Files: <code>meson.build</code></sub>
  - <sub>Keywords: <code>dependency</code></sub>
- [x] [<code>Headerbar: code style, small fixes (#1234)</code>](https://github.com/elementary/code/commit/d2ef5f1531b2fbc3ea9901d6e5250f2fe3b0cbaf)
- [x] [<code>Metainfo: Add 7.0.0 release notes (#1246)</code>](https://github.com/elementary/code/commit/c77372d99317e8cf7d0be3d15582ab7db5577355)
- [x] [<code>MetaInfo: update min-length</code>](https://github.com/elementary/code/commit/78b696c574aae1577e06f3bfb0f76cd56083b9ac)
- [x] [<code>Application: use built-in GLib functions in Activate (#1243)</code>](https://github.com/elementary/code/commit/96bc1ca156a322109272d09adccef3ab4ee0e377)
- [x] [<code>Inactivate find actions when no current doc (#1251)</code>](https://github.com/elementary/code/commit/9e9c3ef5d9e8799fbe2b5aab3aec47e2d83ca282)
- [x] [<code>Fix startup warnings (#1250)</code>](https://github.com/elementary/code/commit/8b55723fddda6911647a5a7c4015d4389399bc6e)
- [x] [<code>Styles: misc refinements (#1226)</code>](https://github.com/elementary/code/commit/bcf9c3b4600b9dd8373e6ac841388343e7faad7e)
- [x] [<code>Release 7.0.0 (#1247)</code>](https://github.com/elementary/code/commit/789487b06acc31aa62527176a79fbd5b56632424)
  - <sub>Tags: <code>7.0.0</code></sub>
  - <sub>Files: <code>meson.build</code></sub>
