### ISSUE TITLE
LightDM 1.32.0

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#2]
### [lightdm](https://github.com/CanonicalLtd/lightdm): [1.30.0 → 1.32.0](https://github.com/CanonicalLtd/lightdm/compare/1.30.0...1.32.0)

- [ ] [<code>On systems without clearenv() the environ variable must be imported as external before it can be manipulated to reset the environment.</code>](https://github.com/CanonicalLtd/lightdm/commit/1b99bc2ed9ad5093ab8b4c7b8ed46b3a04bfcc65)
- [x] ~~[<code>Move D-Bus conf file to $(datadir)/dbus-1/system.d</code>](https://github.com/CanonicalLtd/lightdm/commit/a99376f5f51aa147aaf81287d7ce70db76022c47)~~
- [x] [<code>Update GitHub/Travis links</code>](https://github.com/CanonicalLtd/lightdm/commit/d36237b29f9a55ae44e204d6480d3cea0ee46c7e)
- [x] [<code>Update debian/</code>](https://github.com/CanonicalLtd/lightdm/commit/2f532f2be251dc7b3abb004e0b96a60750f28598)
- [ ] [<code>Move plmouth from depends to recommends</code>](https://github.com/CanonicalLtd/lightdm/commit/9a728a68debe28af4e121aa4b5406d90772e10f2)
- [x] [<code>Update README.md</code>](https://github.com/CanonicalLtd/lightdm/commit/2bf17755cc2fffdf9e66b34e9f78a82e43b1faf2)
- [x] [<code>Drop Qt 4 support, it's been unsupported since 2015</code>](https://github.com/CanonicalLtd/lightdm/commit/e847a5d30780d010bfb776378dea51789efc26df)
- [ ] [<code>Clean up dbus conf format</code>](https://github.com/CanonicalLtd/lightdm/commit/fa30fc604c5f54cc10ef165d3c577ddd79afc637)
- [x] ~~[<code>Determine a session is wayland with a better heuristic</code>](https://github.com/CanonicalLtd/lightdm/commit/03f218981733e50d810767f9d04e42ee156f7feb)~~
- [ ] [<code>Only set LANGUAGE if not in a live session</code>](https://github.com/CanonicalLtd/lightdm/commit/89e737dba129f514e6b8947a9b6fd277c531e9c3)
- [ ] [<code>Update lightdm-gtk-greeter URL</code>](https://github.com/CanonicalLtd/lightdm/commit/fe818e65b204280c5189ea7b4a77363c0d774f1b)
- [ ] [<code>Make some private functions static</code>](https://github.com/CanonicalLtd/lightdm/commit/a90d07e236934a8f1320c92da8819213eabbed57)
- [x] [<code>Fix Ubuntu CI stalling on debconf prompt</code>](https://github.com/CanonicalLtd/lightdm/commit/02fa01c67289d5dfcd2287a6cd2c46090884ac69)
- [ ] [<code>Fix: "DesktopManager" -> "DisplayManager"</code>](https://github.com/CanonicalLtd/lightdm/commit/6b9b538d76a52570df8f4999ff2e0c482913dd23)
- [x] [<code>Add CLA check</code>](https://github.com/CanonicalLtd/lightdm/commit/f3fa27eeeef9aa902d27ec33b90111c79525635d)
- [x] [<code>Add test GitHub action</code>](https://github.com/CanonicalLtd/lightdm/commit/97dc99a3a7a20ecf4db15b9536bd82a79078a8d5)
- [ ] [<code>Glibc 2.33 fix.</code>](https://github.com/CanonicalLtd/lightdm/commit/270b3bfcf84939ab2d71db3f3470cffd36816852)
- [ ] [<code>Handle Python 3 use of bytes</code>](https://github.com/CanonicalLtd/lightdm/commit/813f048ced1bd91bf82f94b4ad97bd7c47590058)
- [ ] [<code>Handle Python 3 sort method changes</code>](https://github.com/CanonicalLtd/lightdm/commit/fd42ffd428f3a0a7ea40f0eb846308a60dbede09)
- [ ] [<code>Require python 3 for the tests</code>](https://github.com/CanonicalLtd/lightdm/commit/c34235b07347ba46eae26c00127f675b653d21b5)
- [x] [<code>ci: Ensure all matrix jobs are run</code>](https://github.com/CanonicalLtd/lightdm/commit/0fe2db31a936dcac6bf6c3bb2ac9e1212fbc8e93)
- [x] [<code>ci: Install dbus for tests</code>](https://github.com/CanonicalLtd/lightdm/commit/93ff600f57981f0c5bd715b30b21ad903bc88eb7)
- [x] [<code>ci: Install Python</code>](https://github.com/CanonicalLtd/lightdm/commit/f40dc739174944805bcf9e6badc3cfc7fdb9c520)
- [x] [<code>ci: Upload test log</code>](https://github.com/CanonicalLtd/lightdm/commit/accf296ef43663f503a0a0bf29dc9d9d2dd38549)
- [x] [<code>ci: Remove Travis CI</code>](https://github.com/CanonicalLtd/lightdm/commit/f3a9422099705f39eec0b308dba4a4c914309525)
- [x] [<code>ci: Disable flaky test</code>](https://github.com/CanonicalLtd/lightdm/commit/257983cc1ed4cf3719b2eb1dd2665b710665bbab)
- [ ] [<code>Remove deprecated use of G_TYPE_INSTANCE_GET_PRIVATE</code>](https://github.com/CanonicalLtd/lightdm/commit/641eb8cb40fc397421a3284025769c590ebee868)
- [ ] [<code>Fix documentation build warnings</code>](https://github.com/CanonicalLtd/lightdm/commit/2928b4dcac5c0397e7c644eed96d95c8b14df0ca)
- [ ] [<code>Stop using deprecated G_PARAM_PRIVATE</code>](https://github.com/CanonicalLtd/lightdm/commit/6a6bd4183144427995634011ea19c7dd32e5306c)
- [ ] [<code>Replace deprecated QAbstractItemModel::setRoleNames</code>](https://github.com/CanonicalLtd/lightdm/commit/a13ac8cff6e88674ac5cd289f1c1f576216686a8)
- [ ] [<code>Use a size_t to resolve a compile warning</code>](https://github.com/CanonicalLtd/lightdm/commit/a8a8eeb1023c1bd89b75c8097072b007f9d79ce7)
- [ ] [<code>Use has-signed-canonical-cla GitHub Action</code>](https://github.com/CanonicalLtd/lightdm/commit/7e3b2b79d26a21958b7217968dbe74ce2e2bc290)
- [x] [<code>Update CLA check so it can write comments</code>](https://github.com/CanonicalLtd/lightdm/commit/98ed207cd9ffdac9e7443c26ede716d3f074760b)
- [ ] [<code>fix: use g_autofree in x_authority_load</code>](https://github.com/CanonicalLtd/lightdm/commit/a02b4ee578f99a9c34fc98f2a4a4cde2f2a25053)
- [x] [<code>Remove Travis badge - now using GitHub actions</code>](https://github.com/CanonicalLtd/lightdm/commit/653809c387c0a4e4d96f7999db3106d89970d4c7)
- [ ] [<code>Update x-authority.c</code>](https://github.com/CanonicalLtd/lightdm/commit/42dc9dc5865d26ba37ca3c07d3a97d4de03b7909)
- [ ] [<code>Mock __getgroups_chk to fix tests on recent glibc</code>](https://github.com/CanonicalLtd/lightdm/commit/7099dec662a9ab77637ecd579ba743a1233fcad4)
- [ ] [<code>Remove unused build rules for removed QT4 support</code>](https://github.com/CanonicalLtd/lightdm/commit/b70ad6bfd1cecb6b3bdee0206dfe937756606a6e)
- [ ] [<code>Fix URL capitalization</code>](https://github.com/CanonicalLtd/lightdm/commit/291d93ecb065092e31267a5798c51e9aad2aefb5)
- [x] [<code>Update to main branch name in URL</code>](https://github.com/CanonicalLtd/lightdm/commit/cbabe8bd7517d8d59922e6bc2e31d0cc972ff4a1)
- [x] [<code>Fix CI failing now master was renamed to main</code>](https://github.com/CanonicalLtd/lightdm/commit/b7fc3214cbaed09c73e963847443a0d648dfd896)
- [ ] [<code>Fix test build failing on older versions of glibc without __getgroups_chk</code>](https://github.com/CanonicalLtd/lightdm/commit/ea7193b94db9b2ef7205353000f95b4629107871)
- [ ] [<code>Fix check for __getgroups_chk</code>](https://github.com/CanonicalLtd/lightdm/commit/7c0d356ab196c9a1f40d52dbb611900e37c52b88)
- [ ] [<code>Add __getgroups_chk prototype to fix build failures on some systems</code>](https://github.com/CanonicalLtd/lightdm/commit/6f40639f4d735333c05fe076704ad2b3e95923c7)
- [ ] [<code>test-runner.c: Fix: Make the test runner aware of the --with-greeter-session configuration parameter</code>](https://github.com/CanonicalLtd/lightdm/commit/ae4b2901ae7872b3e90a8866165289419dd05672)
- [ ] [<code>test-runner.c: Fix: Make the test runner aware of the --with-greeter-user configuration parameter</code>](https://github.com/CanonicalLtd/lightdm/commit/9abb4baec7b740476401456ec961acd036afdd23)
- [ ] [<code>test-runner.c: Fix: Make the test configuration files aware of the --with-greeter-user configuration parameter</code>](https://github.com/CanonicalLtd/lightdm/commit/cc0160667e8a3b132236a7bf5776c3865c481b7b)
- [ ] [<code>Disable compiler optimizations for test programs</code>](https://github.com/CanonicalLtd/lightdm/commit/224b090ed78abbf43ca75f825dba78966c97c082)
- [ ] [<code>Fix inconsistency between lightdm_get_layout and lightdm_set_layout</code>](https://github.com/CanonicalLtd/lightdm/commit/a3f5981b35b19625daf0c67c2a5d999f8ee74222)
- [x] [<code>Disable Ubuntu tests for now, until we can work out why they are failing</code>](https://github.com/CanonicalLtd/lightdm/commit/40c3b4d4cfd747707bae1fe3953527dcff650213)
- [ ] [<code>Fix test against arrays that can never be NULL</code>](https://github.com/CanonicalLtd/lightdm/commit/1d1d1e4196b81147cf898ac6dfbe30fcd25d6b2d)
- [x] [<code>No longer making releases</code>](https://github.com/CanonicalLtd/lightdm/commit/80147e515513261226d01a32c8b0c819f84e21e8)
- [x] [<code>Mailing list closed - use forum now</code>](https://github.com/CanonicalLtd/lightdm/commit/756d2323ad615e0ec98fa273c611de7b07ee2ca5)
- [ ] [<code>Don't call setenv with a NULL value - the behaviour is undefined.</code>](https://github.com/CanonicalLtd/lightdm/commit/35326597c2f5d1e42c56feaf7f8aedac9c9d14ff)
- [ ] [<code>config: set `logind-check-graphical=True` per default</code>](https://github.com/CanonicalLtd/lightdm/commit/77a7c6b7b8ca896b98ef43826641bdd520650bfb)
- [x] [<code>Update Chinese (Taiwan) Translations.</code>](https://github.com/CanonicalLtd/lightdm/commit/9f2568af7143d99b707290f423ffb918a962e2e0)
- [x] [<code>Update az.po</code>](https://github.com/CanonicalLtd/lightdm/commit/bb330c5db3966e4b9268b93645410f3ce4a557d6)
- [x] [<code>Update oc.po</code>](https://github.com/CanonicalLtd/lightdm/commit/c8d8a4bf0bbba8d7ee84efd28b4d6a95945745d9)
- [ ] [<code>fix: block login if shell in nologin or false</code>](https://github.com/CanonicalLtd/lightdm/commit/0c21d986ff3c9ec1568b681c746e30b6fd25d5cb)
- [ ] [<code>Work around a race with password-less logins and double clicks</code>](https://github.com/CanonicalLtd/lightdm/commit/fe117f074137c38828076c14989e4c0ebbcb41aa)
- [ ] [<code>Fix crash due to using wrong method to set configuration</code>](https://github.com/CanonicalLtd/lightdm/commit/3fd8d5c0d909d4b7e8cab285a08410796cc69e69)
- [x] [<code>Fix tests broken by default config change in 77a7c6b7b8ca896b98ef43826641bdd520650bfb</code>](https://github.com/CanonicalLtd/lightdm/commit/506e4220f2d9041ffa4124cab18810aec6cb9b8b)
- [ ] [<code>Fix distcheck failure due to intltool file being left behind</code>](https://github.com/CanonicalLtd/lightdm/commit/792baa54a53598fb46cbdec675e28f5d72d211eb)
- [ ] [<code>Releasing 1.32.0</code>](https://github.com/CanonicalLtd/lightdm/commit/4b10d07b7bf87668a245b438b5ffc82e3956bd1c) <sub>Tagged: <code>1.32.0</code></sub>

### [github:Xubuntu/lightdm-gtk-greeter](https://github.com/Xubuntu/lightdm-gtk-greeter): [lightdm-gtk-gree → HEAD](https://github.com/Xubuntu/lightdm-gtk-greeter/compare/lightdm-gtk-greeter-2.0.7...HEAD)

- [x] [<code>Use 'Large Text' instead of 'Large Font' (LP: #1829070)</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/18563bc3e24c49d98aed8eaadd3f74cdc115079f)
- [x] [<code>Replace ungrammatical comma splice in 'Incorrect password' message (LP: #1810143)</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/a8e3bdbcf19bd88159dfd847efd34de041ff75a2)
- [x] [<code>Allow building with newer versions of gettext</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/5fb5c3c9a4be9ac42abd91cd5c5d074e7c390fca)
- [x] [<code>Refresh translations from Launchpad</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/75729ed8d9fe55125b401c0b75d53a2d4f7bf272)
- [x] [<code>Restore lightdm-gtk-greeter.pot</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/53a42c7932df2d4c6002bf21efcf6c5e0b7007db)
- [x] [<code>Fix .pot file location</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/736b8627ac9657f5e6bf0a21d6bbf8eb3f5c1eb0)
- [x] [<code>Update README</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/66d99e498bd37455f298e4a853a6c45225236aec)
- [x] [<code>Update URLs</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/a282457a9e0755c7230aee8d7bcdf0c495c7f0c1)
- [x] [<code>Update copyright email</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/7e704196d0b0cd531a8ed51580beb5777f140bf9)
- [ ] [<code>Move from exo-csource to xdt-csource</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/9595aee9a309a46dba96fa9f7d3f6f01da34bc4c)
- [ ] [<code>greeterbackground: Fix deprecated instance private data API</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/bb3c590d7c6c803ad949f76582b9d514c0cfb283)
- [ ] [<code>Drop xdg-csource dependency outside of maintainer mode (detected via autogen.sh) (fixes #53)</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/97e7ac3a59c16e82b19735d8a56470ac47eb59d1)
- [x] [<code>Create distcheck.yml</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/3de19065f86dd5270464a39a08d813481f42cb70)
- [x] [<code>workflows/distcheck: Run apt update first</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/c046132e9263feab156c4f95971bd8728b8a9c75)
- [x] [<code>workflows/distcheck: Add git2cl dependency</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/3e6c7f8a47e7f958aa631d0fe7b1c6e1e1ecb438)
- [x] [<code>Refresh copyrights</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/925c25279d1851d8dc87b9442d36638186d7c2c6)
- [x] [<code>Update changelog</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/af2287e149d580fe35b5b77aaf5f30d4ea545c74)
- [ ] [<code>Add support for Ayatana indicators (fixes #74)</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/9c50d93d3c52623183e3562ed3f033533a672fbc)
- [ ] [<code>Fix loading Unity and Ayatana indicators</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/33fdde12ed0d6a4e900d86422cf50fa1d33fa724)
- [ ] [<code>Respect XDG autostart paths</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/d797072d729dce47d7cff155ca8c15756db6f6f8)
- [ ] [<code>Improve builds and error handling</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/5c4ff6ef2e21ce97391401df4e52ec4d9a47ba54)
- [x] [<code>Update for 2.0.8 release</code>](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/8008f297f7d0b34b875a837d41f77cf57e7b3f7c) <sub>Tagged: <code>lightdm-gtk-greeter-2.0.8</code></sub>

**Comment by bobby285271** [comment]
Closing as the PR has been merged.
