### ISSUE TITLE
Cinnamon updates 2022-08-10

### ISSUE THREAD

**Issue by bobby285271** [bobby285271/what-changed#3]
### [cinnamon.cinnamon-common](https://github.com/linuxmint/cinnamon): [5.4.8 → 5.4.9](https://github.com/linuxmint/cinnamon/compare/5.4.8...5.4.9)

- [x] [<code>sound applet: Fix the context menu's input mute icon.</code>](https://github.com/linuxmint/cinnamon/commit/bc58cf26559a126a516ef64f22593d9788f84d14)
- [x] [<code>thumbails: Update the Adwaita thumbnails for cs_themes (#10968)</code>](https://github.com/linuxmint/cinnamon/commit/fc09a50236ea4e4aca0ae91f35551ac4e6b49fe7)
- [x] [<code>Imported submodule explicitly from PIL to fix bug (#10955)</code>](https://github.com/linuxmint/cinnamon/commit/e7d83d98666cfa61ddf73f01d3aefb955622c744)
- [x] [<code>cinnamon-gtk-embed: Clamp transparency of the tray icon's underlying</code>](https://github.com/linuxmint/cinnamon/commit/100124235fc3509a0f6ca84c11300dbb7e387c26)
- [x] [<code>cinnamon-window-tracker: Use a different method for matching</code>](https://github.com/linuxmint/cinnamon/commit/9453e6576367491cb7f20a14018fe8ad521d3da7)
- [x] [<code>gwl: Fix updating tooltips and previews when the applet's panel</code>](https://github.com/linuxmint/cinnamon/commit/d0b2654b6e43d1537eaaeb9ee6011ea64395d93e)
- [x] [<code>windowManager: Fix a missing default case, return early when</code>](https://github.com/linuxmint/cinnamon/commit/b908d1c2ce7db2a125c81a9aa761334b70e1631a)
- [x] [<code>signalManager: Make it slightly easier to debug signals and access-</code>](https://github.com/linuxmint/cinnamon/commit/227bfce0625d977e160a565de21140aa2fa8f7a9)
- [x] [<code>gwl: Disconnect size notify signals from actors when they become</code>](https://github.com/linuxmint/cinnamon/commit/9aff11cd26a3a8b2f135ba1076e3b5d3f8193d50)
- [x] [<code>windowManager.js: Fix gtk popup menu animations.</code>](https://github.com/linuxmint/cinnamon/commit/414f93a8747f8e50475becfaed03fe17f65ac302)
- [x] [<code>5.4.9</code>](https://github.com/linuxmint/cinnamon/commit/3b8951121fd220481ae9d892101f90660f4e6e61) <sub>Tagged: <code>5.4.9</code></sub>

### [cinnamon.cinnamon-control-center](https://github.com/linuxmint/cinnamon-control-center): [5.4.4 → 5.4.6](https://github.com/linuxmint/cinnamon-control-center/compare/5.4.4...5.4.6)

- [x] [<code>build: add missing gio-unix-2.0 dependency (#294)</code>](https://github.com/linuxmint/cinnamon-control-center/commit/7f5ba6e7a691547840f8482445c09c729e10a397)
- [x] [<code>5.4.5</code>](https://github.com/linuxmint/cinnamon-control-center/commit/1c476eee4136298eba01eb1994845b5247f5e06f) <sub>Tagged: <code>5.4.5</code></sub>
- [x] [<code>wacom: Bring in line with changes in muffin to fix support.</code>](https://github.com/linuxmint/cinnamon-control-center/commit/23ba1437a5e5375cb6243dee1110cd766746bc3f)
- [x] [<code>5.4.6</code>](https://github.com/linuxmint/cinnamon-control-center/commit/b612583036b969a1936e8ec11723355864f6b4bb) <sub>Tagged: <code>5.4.6</code> <code>master.lmde5</code> <code>master.mint21</code></sub>

### [cinnamon.cinnamon-screensaver](https://github.com/linuxmint/cinnamon-screensaver): [5.4.1 → 5.4.2](https://github.com/linuxmint/cinnamon-screensaver/compare/5.4.1...5.4.2)

- [x] [<code>build: Try to find libxdo with pkgconfig, and use find_library()</code>](https://github.com/linuxmint/cinnamon-screensaver/commit/7673a6c136ab66e3670919460a87f8887f0ba9b7)
- [x] [<code>Don't try to throw an error if libxdo can't be found - meson will</code>](https://github.com/linuxmint/cinnamon-screensaver/commit/cfd87cb63316608e7f2a64f68eedcc09cc03d0da)
- [x] [<code>libcscreensaver: add missing gio-unix-2.0 dependency (#411)</code>](https://github.com/linuxmint/cinnamon-screensaver/commit/8d658e7f313879579322dce666551f132795540b)
- [x] [<code>5.4.2</code>](https://github.com/linuxmint/cinnamon-screensaver/commit/c9ae1cef31a01a715140d631044556888a00aeab) <sub>Tagged: <code>5.4.2</code> <code>master.lmde5</code> <code>master.mint21</code></sub>

### [cinnamon.cinnamon-settings-daemon](https://github.com/linuxmint/cinnamon-settings-daemon): [5.4.3 → 5.4.5](https://github.com/linuxmint/cinnamon-settings-daemon/compare/5.4.3...5.4.5)

- [x] [<code>csd-wacom: Remove unused functionality.</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/88e9de536db46ed1bda3777d24e9305d694099c6)
- [x] [<code>debian/control: Add missing pango dependency, move its meson entry</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/928e0ebcb33e9e56fe0631476e7df4e831c174f0)
- [x] [<code>schemas: Fix wacom schema names for migrate_check.</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/a34e269cb771d989b4689acca15edc622065d18b)
- [x] [<code>schemas: Add missing desktop schema for migration.</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/dff79fabd3e0496fc0d7b693f4c00bda798a00a1)
- [x] [<code>5.4.4</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/a33cd01bc45e96bd165717be291e1dc9cea5d578) <sub>Tagged: <code>5.4.4</code></sub>
- [x] [<code>meson options: Set debug flag back to false.</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/cde270d2a41a750493b142cd721abbd3abcd3b83)
- [x] [<code>Fix broken rpath (#367)</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/07b7a670ef6fb2d9cd2b80ee397c1f2de2f9ba0a)
- [x] [<code>wacom: Don't set an rpath for led helpers.</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/e06680ce2db03045c1030be66315a1e382b4a734)
- [x] [<code>Small packaging improvements (#368)</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/883ec8deca8d10cf1b2608969f415bb83949c84c)
- [x] [<code>5.4.5</code>](https://github.com/linuxmint/cinnamon-settings-daemon/commit/6ccf37c4a6df93c809d17de5b90ec643e7146347) <sub>Tagged: <code>5.4.5</code> <code>master.lmde5</code> <code>master.mint21</code></sub>

### [cinnamon.mint-themes](https://github.com/linuxmint/mint-themes): [2.0.3 → 2.0.4](https://github.com/linuxmint/mint-themes/compare/38b5606c3889a9a0bac0e2ab39196f675496982c...73d6cfea807ea84a645f43424c60916cb6214693)

- [x] [<code>Mint-Y-Gtk3: Fix dragging in the Nemo sidebar</code>](https://github.com/linuxmint/mint-themes/commit/207ee1d658633d87e70ad69cbace3d9582a1796e)
- [x] [<code>2.0.4</code>](https://github.com/linuxmint/mint-themes/commit/73d6cfea807ea84a645f43424c60916cb6214693)

### [cinnamon.mint-y-icons](https://github.com/linuxmint/mint-y-icons): [1.6.0 → 1.6.1](https://github.com/linuxmint/mint-y-icons/compare/6294c4538a08a2a6c5fd68e223472d9c144ff8b0...57d16eb85f2af40be17e2232d279bb65b689f5b7)

- [x] [<code>Add star symbolics</code>](https://github.com/linuxmint/mint-y-icons/commit/fa3bbf2d81a2562e44a70fd51829e24d472795ce)
- [x] [<code>1.6.1</code>](https://github.com/linuxmint/mint-y-icons/commit/57d16eb85f2af40be17e2232d279bb65b689f5b7)

### [cinnamon.muffin](https://github.com/linuxmint/muffin): [5.4.4 → 5.4.5](https://github.com/linuxmint/muffin/compare/5.4.4...5.4.5)

- [x] [<code>fix a spelling error spotted by lintian</code>](https://github.com/linuxmint/muffin/commit/52a81921654b2ecb07cbc464fed16f71a788fab5)
- [x] [<code>window.c: Allow tiling in any monitor orientataion.</code>](https://github.com/linuxmint/muffin/commit/c2c62e71a8b5149f577171929156451906e4728c)
- [x] [<code>tiling: Disable drag-to-maximize behavior if tiling is disabled,</code>](https://github.com/linuxmint/muffin/commit/84a91d99c05f335b69d4e147a9644de15f822b90)
- [x] [<code>5.4.5</code>](https://github.com/linuxmint/muffin/commit/930de9efb318ef21dd5a12ff48972305cb21890b) <sub>Tagged: <code>5.4.5</code> <code>master.lmde5</code> <code>master.mint21</code></sub>

### [cinnamon.xviewer](https://github.com/linuxmint/xviewer): [3.2.9 → 3.2.10](https://github.com/linuxmint/xviewer/compare/3.2.9...3.2.10)

- [x] [<code>Fix Batch Save - issue #168 (#169)</code>](https://github.com/linuxmint/xviewer/commit/8f6f766c905b883eed24d30a11a701f1cb655f71)
- [x] [<code>3.2.10</code>](https://github.com/linuxmint/xviewer/commit/af24bee9780680f0f8051e84e7afc43d1c283beb) <sub>Tagged: <code>3.2.10</code> <code>master.lmde5</code></sub>

### [xplayer](https://github.com/linuxmint/xplayer): [2.4.3 → 2.4.4](https://github.com/linuxmint/xplayer/compare/2.4.3...2.4.4)

- [x] [<code>l10n: Update translations</code>](https://github.com/linuxmint/xplayer/commit/639a966aaaee04e5e65dd22f82bc2b59684364ae)
- [x] [<code>2.4.4</code>](https://github.com/linuxmint/xplayer/commit/2d2700a08d67a92420e8ca775fab8167d42d57b0) <sub>Tagged: <code>2.4.4</code></sub>
